service: io-node-challenge
provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage,'DESA'}
  region: us-east-2
  timeout: 15
  logRetentionInDays: ${self:custom.logRetentionInDays.${self:provider.stage}}
  environment: ${file(config/environments.yaml)}
  iamRoleStatements: ${file(config/iam-role-statements.yaml)}
custom:
  reducer:
    ignoreMissing: true
  seed:
    seedUsersTable: ${file(config/dynamodb-seed.yaml):seedUsersTable}
  logRetentionInDays: ${file(./config/common-custom-config.yaml):logRetentionInDays}
plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-plugin-reducer
  - serverless-dynamodb-seed
  - serverless-step-functions
  - serverless-dynamodb-stream-arn-plugin
package:
  individually: true
  exclude:
    - npm-cache/**
functions: ${file(config/functions.yaml)}
resources: ${file(config/resources.yaml)}
stepFunctions: ${file(config/stepfunctions.yaml)}